### ISSUE TITLE
xd

### ISSUE THREAD

**Issue by intercoursewithyourmom** [doomed-phobos/cppython#1]
holaa, soy sofía, no se si me recuerdes, decidí hablarte por aquí pq desapareciste de insta hace un buen y me acorde que tenias perfil aquí, y creo que eres mas activo por aca, eh, espero estés bien <3 

pd: no se como se usa GitHub, me cree la cuenta para ver si podia doxxear a alguien de Facebook pero no funcionó  xd

xd

**Comment by doomed-phobos** [comment]
yandere :v
